jobs:
  build-and-test:
    working_directory: ~/meteor
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - .node_modules
      - run:
          name: Run Tests
          command: npm run test:unit
  package:
    working_directory: ~/meteor
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build for production
          command: npm run build -- --modern
      - run:
          name: zip dist
          command: zip -r meteor-dist.zip ./dist
      - store_artifacts:
          path: meteor-dist.zip
workflows:
  version: 2
  build-test-and-approval-package:
    jobs:
      - build-and-test
      - hold:
          type: approval # requires that an in-app button be clicked by an appropriate member of the project to continue.
          requires:
            - build-and-test
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
      - package:
          requires:
            - hold
