jobs:
  install:
    working_directory: ~/meteor
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: npm-cache-v1-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/meteor
          paths:
            - node_modules
  jest:
    working_directory: ~/meteor
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/meteor
      - run:
          name: Run Tests
          command: npm run test:unit
  cypress:
    working_directory: ~/meteor
    machine: true
    steps:
      - checkout
      - run:
          name: remove babel config (bug with Cypress)
          command: rm ./babel.config.js
      - run:
          name: Start CI
          command: ssh open-sky.fr "~/env-ci.sh start"
      - run:
          name: Run cypress tests
          command: |
            docker run -it -v ~/meteor:/e2e -w /e2e cypress/included:3.2.0 run --config baseUrl=https://ci.meteor.open-sky.fr
      - run:
          name: Stop CI
          command: ssh open-sky.fr "~/env-ci.sh stop"
          when: always
  package:
    working_directory: ~/meteor
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - attach_workspace:
          at: ~/meteor
      - run:
          name: Build for CI
          command: npm run build -- --modern --mode ci
      - run:
          name: zip dist
          command: zip -r meteor-dist.zip ./dist
      - store_artifacts:
          path: meteor-dist.zip
      - persist_to_workspace:
          root: ~/meteor
          paths:
            - dist
            - ansible
  deploy:
    working_directory: ~/meteor
    docker:
      - image: ansible/ansible-runner
    steps:
      - add_ssh_keys:
          fingerprints:
            - "5f:7e:ed:8d:47:13:0a:7e:8e:c4:72:b5:18:75:17:71"
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/meteor
      - run: |
          ssh-keyscan -H open-sky.fr >> ~/.ssh/known_hosts
      - run:
          name: Playbook time
          command: |
            cd ~/meteor/ansible
            ansible-playbook -i inventory open-sky.fr.yml
workflows:
  version: 2
  build-test-and-approval-package:
    jobs:
      - install
      - jest:
          requires:
            - install
      - package:
          requires:
            - jest
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - package
      - cypress:
          requires:
            - deploy
          filters:
            branches:
              only: master
